parent <- "~/Documents/heavymesons/data/newinput"
folders <- c("cB211.07.48_novariation", "cB211.07.48_vary")
nameshort <- c("B48_novariation", "B48_vary")
subfolders  <- c("th2", "th4", "th6", "th8", "th9.5")

infos <- read.table("parameters_input_files.csv", row.names=1, header=TRUE, sep=",", comment.char = "#")

## time separations and volumes

index <- 1
for(kernel in c("sigmoid", "erf")){
    for(channel in c("cd", "cs")) {
fileDG <- sprintf("%s/%s-compare-stability-quarkmasses-%s-%s.Rmd", parent, 210+index, channel, kernel)


cat(sprintf("```{r setupsummarytimesep%s%s, include=FALSE}", channel, kernel), 
"knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, results = FALSE)", 
"source(\"/home/gross/Documents/heavymesons/scripts_christiane/extrapolate_sigma_templates/functions_stability_plots.R\")", 
"source(\"/home/gross/Documents/heavymesons/scripts_christiane/extrapolate_sigma_templates/calc_DGDq2.R\")", 
"library(\"hadron\")", 
"zlist <- c(3, 0, 1, 2)", 
"errlist <- c(\"stat\")", 
"sumup <-FALSE", 
"```",
"", 
sprintf("# Differential Decay Rates - quark masses %s %s\n", channel, kernel),
file=fileDG, append=FALSE, sep="\n")


        for(th in c(2, 4, 6, 8, 9.5)) {
            cat(
            sprintf("## %s %s th %s\n", channel, kernel, th),
            "### Z\n",
            sprintf("```{r quarkmassZ%s%sth%s}", channel, kernel, th),
            sprintf("thpath1 <- \"/home/gross/Documents/heavymesons/data/%s/cB211.07.48_novariation/th%s/%s_new/outputDGammaDq2/\"", channel, th, kernel),
            sprintf("thpath2 <- \"/home/gross/Documents/heavymesons/data/%s/cB211.07.48_vary/th%s/%s_new/outputDGammaDq2/\"", channel, th, kernel),
            sprintf("thpath3 <- \"/home/gross/Documents/heavymesons/data/%s/cB211.07.48_strange/th%s/%s_new/outputDGammaDq2/\"", channel, th, kernel),
            sprintf("thpath4 <- \"/home/gross/Documents/heavymesons/data/%s/cB211.07.48_charm/th%s/%s_new/outputDGammaDq2/\"", channel, th, kernel),
            sprintf("thpath5 <- \"/home/gross/Documents/heavymesons/data/%s/cB211.07.48_charm_strange/th%s/%s_new/outputDGammaDq2/\"", channel, th, kernel),
#~             "plotZsets(pathlist=c(thpath1, thpath2, thpath3, thpath4, thpath5), iz=0, main=\"Z 0\",", 
#~             "          comments=c(\"un\", \"va\", \"st\", \"ch\", \"cs\"))",
            #"          comments=c(\"unchanged\", \"varied\", \"charm changed\", \"strange changed\", \"charm, strange changed\"))",
#~             "plotZsets(pathlist=c(thpath1, thpath2, thpath3, thpath4, thpath5), iz=1, main=\"Z 1\",",  
#~             "          comments=c(\"un\", \"va\", \"st\", \"ch\", \"cs\"))",
#~             "plotZsets(pathlist=c(thpath1, thpath2, thpath3, thpath4, thpath5), iz=2, main=\"Z 2\",",  
#~             "          comments=c(\"un\", \"va\", \"st\", \"ch\", \"cs\"))",
            "plotZsets(pathlist=c(thpath1, thpath2), iz=0, main=\"Z 0\",", 
            "          comments=c(\"un\", \"va\"))",
#~             #"          comments=c(\"unchanged\", \"varied\", \"charm changed\", \"strange changed\", \"charm, strange changed\"))",
            "plotZsets(pathlist=c(thpath1, thpath2), iz=1, main=\"Z 1\",",  
            "          comments=c(\"un\", \"va\"))",
            "plotZsets(pathlist=c(thpath1, thpath2), iz=2, main=\"Z 2\",",  
            "          comments=c(\"un\", \"va\"))",
            "```\n",
            "### stability AA0\n",
            sprintf("```{r quarkmassstability%s%sth%s, eval=!(knitr::is_html_output())}", channel, kernel, th),
#~             sprintf("plot_stability_AA0_sets(pathlist=c(thpath1, thpath2, thpath3, thpath4, thpath5), inputfile=paste0(thpath1, \"/../../DGammaDq2_%s_new.in\"),", kernel), 
#~             "                            nnorm=3, neps=19, zlist=-1, normseq=c(1),", 
#~             "          comments=c(\"un\", \"va\", \"st\", \"ch\", \"cs\"),",
#~             "                            comblist=c(0))",
            sprintf("plot_stability_AA0_sets(pathlist=c(thpath1, thpath2), inputfile=paste0(thpath1, \"/../../DGammaDq2_%s_new.in\"),", kernel), 
            "                            nnorm=3, neps=19, zlist=-1, normseq=c(1),",
            "                            comments=c(\"unchanged\", \"varied\"),",
            "                            comblist=c(0))",
            "```\n",
file=fileDG, append=TRUE, sep="\n")
        }
    index <- index+1
    }
}


fileDG <- sprintf("%s/%s-compare-decay-rate-quarkmasses.Rmd", parent, 200+5)
cat(sprintf("```{r setupextrpolationquarkmasses, include=FALSE}"), 
"knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, results = FALSE)", 
"source(\"/home/gross/Documents/heavymesons/scripts_christiane/extrapolate_sigma_templates/functions_stability_plots.R\")", 
"source(\"/home/gross/Documents/heavymesons/scripts_christiane/extrapolate_sigma_templates/calc_DGDq2.R\")", 
"source(\"/home/gross/Documents/heavymesons/scripts_christiane/extrapolate_sigma_templates/calc_DGDq2_aic.R\")", 
"library(\"hadron\")", 
"zlist <- c(3, 0, 1, 2)", 
"errlist <- c(\"stat\")", 
"sumup <-FALSE", 
"```",
"", 
file=fileDG, append=FALSE, sep="\n")

for(kernel in c("sigmoid", "erf")){
    for(channel in c("cd", "cs")) {
        cat(
"",
sprintf("## Extrapolation %s %s\n", channel, kernel),
sprintf("```{r %s%ssetupextrapolationquarkmass}", channel, kernel),
"fneight <- function(par, x, boot.R, ...) par[1] + par[2] * x**2 + par[3] * x**4 + par[4] * x**6 + par[5] * x**8",
"fnfour <- function(par, x, boot.R, ...) par[1] + par[2] * x**2 + par[3] * x**4",
"",
"maxAmin <- 1",
"",
sprintf("       files <- c(\"th2/%s_new/outputDGammaDq2/DGammaDq2.bin\",", kernel),
sprintf("                  \"th4/%s_new/outputDGammaDq2/DGammaDq2.bin\",", kernel),
sprintf("                  \"th6/%s_new/outputDGammaDq2/DGammaDq2.bin\",", kernel),
sprintf("                  \"th8/%s_new/outputDGammaDq2/DGammaDq2.bin\",", kernel),
sprintf("                  \"th9.5/%s_new/outputDGammaDq2/DGammaDq2.bin\")", kernel),
"",
"",
"th <- c(2, 4, 6, 8, 9.5)",
"nerr <- rep(2, 5)",
"tsnk <- rep(48, 5)",
"Nt <- rep(24, 5)",
"",
"par.guess <- rep(1, 5)",
"",
"```",
"",
sprintf("```{r B48quarkmass%s%sextrapolatesigmatozerofinvol}", channel, kernel),
"",
"",
sprintf("savename <- \"tables/DG_quarkmass_cB48_%s_%s\"", channel, kernel),
"",
"par.guess <- rep(1, 5)",
"",
"",
sprintf("fitlist <- determineDGDq2_combine_aic(resultpathlist=list(\"/home/gross/Documents/heavymesons/data/%s/cB211.07.48_novariation/\",", channel),
sprintf("                                                       \"/home/gross/Documents/heavymesons/data/%s/cB211.07.48_vary/\", ", channel),
sprintf("                                                       \"/home/gross/Documents/heavymesons/data/%s/cB211.07.48_strange/\", ", channel),
sprintf("                                                       \"/home/gross/Documents/heavymesons/data/%s/cB211.07.48_charm/\", ", channel),
sprintf("                                                       \"/home/gross/Documents/heavymesons/data/%s/cB211.07.48_charm_strange/\"), ", channel),
"                           filenames = c(files, files, files, files, files), ",
"                           tsnk = tsnk, Nt = Nt, th = th, nerr = nerr, amin = maxAmin, savename = savename,",
"                           fitfnlist = list(fneight, fneight, fneight, fneight, fneight), ",
"                           par.guesslist = list(par.guess, par.guess, par.guess, par.guess, par.guess), ",
"                           errors=c(\"stat\", \"sys\"), doplot=!(knitr::is_html_output()), ",
"                           volumetablelist = rep(\"tables/dummyvolume.csv\", 5),",
"                           numberfits = 5, legendargs=list(x=\"topright\", ncol=1, legend=c(\"un\", \"va\", \"st\", \"ch\", \"cs\")))",
sprintf("saveRDS(object=fitlist, file=\"tables/DG_quarkmass_fitlist_cB48_%s_%s.RDS\")", channel, kernel),
"",
"```",
"### Summary",
"",
sprintf("```{r B48quarkmass%s%ssummaryfinvol}", channel, kernel),
"",
"a <- 0.079570",
"agev <- 0.079570 / 0.1973269804 # fm / hbarc = GeV^-1",
"da <- 0.00013",
"am_H <- 0.800000 # dimensionless",
"conversionfactor <- (am_H/agev)^3/2/pi",
"",
sprintf("savename <- sprintf(\"tables/DG_quarkmass_cB48_%s_%s\")", channel, kernel),
"result <- read.table(paste0(savename, \".csv\"), header=TRUE)",
"",
"result[, c(\"DGDq2gev\", \"dDGDq2gev\")] <- result[, c(\"DGDq2\", \"dDGDq2\")] * conversionfactor",
"result$q <- result$w * am_H / agev",
"result$afm <- rep(a, length(result$q))",
"result$dafm <- rep(da, length(result$q))",
"result",
"",
"for (iz in c(3, 0, 1, 2)) {",
"  for (err in c(\"stat\", \"sys\")){",
"    mask <- result$iz==iz & result$icomb==0 & result$errtype==err & result$fitno > 0",
"    try(plotwitherror(x=result$q[mask]^2+(result$fitno[mask]+1)*0.0005, y=result$DGDq2gev[mask], dy=result$dDGDq2gev[mask],",
sprintf("                      main=paste(\"differential decay rate for tsink=48, tins=36, %s, %s, \", err, \"Z\", iz), ", channel, kernel),
"                      xlab=\"q^2 [GeV^2]\", ylab=\"24 pi^3 DGamma / Dq^2 [GeV^-3]\",",
"                      ylim=c(0, max(result$DGDq2gev[mask] + result$dDGDq2gev[mask])), ",
"                      xlim=c(0, max(result$q[mask]^2+(result$fitno[mask]+1)*0.0005)), col=result$fitno[mask]))",
"    legend(x=\"topright\", col=result$fitno[mask], pch=c(1, 1, 1, 1, 1),",
"           legend=c(\"un\", \"va\", \"st\", \"ch\", \"cs\"))",
"    ",
"    try(plotwitherror(x=result$q[mask]^2+(result$fitno[mask]+1)*0.0005, y=result$dDGDq2gev[mask],",
sprintf("                      main=paste(\"differential decay rate for tsink=48, tins=36, %s, %s, \", err),", channel, kernel),
"                      ylab=\"24 pi^3 d(DGamma / Dq^2) [GeV^-3]\", xlim=c(0, max(result$q[mask]^2)), col=result$fitno[mask]))",
"    legend(x=\"topleft\", col=result$fitno[mask], pch=c(1, 1, 1, 1, 1),",
"           legend=c(\"un\", \"va\", \"st\", \"ch\", \"cs\"))",
"    ",
"  }",
"}",
"for(ith in th) {",
"  for (err in c(\"stat\", \"sys\")){",
"    mask <- result$th==ith & result$icomb==0 & result$errtype==err & result$fitno > 0",
"  plotwitherror(x=result$iz[mask]+0.1*(result$fitno[mask]-1), y=result$DGDq2gev[mask], dy=result$dDGDq2gev[mask],",
sprintf("                      main=paste(\"differential decay rate for tsink=48, tins=36, %s, %s, \", err, \"th\", ith), ", channel, kernel),
"                      xlab=\"Z\", ylab=\"24 pi^3 DGamma / Dq^2 [GeV^-3]\", col=result$fitno[mask], xlim=c(-1, 3.5))",
"    legend(x=\"topleft\", col=result$fitno[mask], pch=c(1, 1, 1),",
"           legend=c(\"un\", \"va\", \"st\", \"ch\", \"cs\"))",
"  }",
"}",
"",
"dat <- readRDS(paste0(savename, \".RDS\"))",
sprintf("savename <- sprintf(\"tables/DG_quarkmass_cB48_%s_%s\")", channel, kernel),
"",
"dat$DGDq2gev <- dat$DGDq2 * conversionfactor",
"dat$dDGDq2gev <- dat$dDGDq2 * conversionfactor",
"dat$datgev <- dat$dat * conversionfactor",
"",
"saveRDS(dat, paste0(savename, \".RDS\"))",
"write.table(result, paste0(savename, \".csv\"))",
"",
"```",
file=fileDG, append=TRUE, sep="\n")
}
}

