parent <- "~/Documents/heavymesons/data/newinput"
folders <- c("cB211.07.48_novariation", "cB211.07.48_vary")
nameshort <- c("B48_novariation", "B48_vary")
subfolders  <- c("th2", "th4", "th6", "th8", "th9.5")

infos <- read.table("parameters_input_files.csv", row.names=1, header=TRUE, sep=",", comment.char = "#")

## time separations and volumes


fileDG <- sprintf("%s/%s-compare-decay-rate-quarkmasses.Rmd", parent, 200+5)
cat(sprintf("```{r setupextrpolationquarkmasses, include=FALSE}"), 
"knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, results = FALSE)", 
"source(\"/home/gross/Documents/heavymesons/scripts_christiane/extrapolate_sigma_templates/functions_stability_plots.R\")", 
"source(\"/home/gross/Documents/heavymesons/scripts_christiane/extrapolate_sigma_templates/calc_DGDq2.R\")", 
"source(\"/home/gross/Documents/heavymesons/scripts_christiane/extrapolate_sigma_templates/calc_DGDq2_aic.R\")", 
"library(\"hadron\")", 
"zlist <- c(3, 0, 1, 2)", 
"errlist <- c(\"stat\")", 
"sumup <-FALSE", 
"```",
"", 
file=fileDG, append=FALSE, sep="\n")

for(kernel in c("sigmoid", "erf")){
    for(channel in c("cd", "cs")) {
        cat(
"",
sprintf("## Extrapolation %s %s\n", channel, kernel),
sprintf("```{r %s%ssetupextrapolationquarkmass}", channel, kernel),
"fneight <- function(par, x, boot.R, ...) par[1] + par[2] * x**2 + par[3] * x**4 + par[4] * x**6 + par[5] * x**8",
"fnfour <- function(par, x, boot.R, ...) par[1] + par[2] * x**2 + par[3] * x**4",
"",
"maxAmin <- 1",
"",
sprintf("       files <- c(\"th2/%s_new/outputDGammaDq2/DGammaDq2.bin\",", kernel),
sprintf("                  \"th4/%s_new/outputDGammaDq2/DGammaDq2.bin\",", kernel),
sprintf("                  \"th6/%s_new/outputDGammaDq2/DGammaDq2.bin\",", kernel),
sprintf("                  \"th8/%s_new/outputDGammaDq2/DGammaDq2.bin\",", kernel),
sprintf("                  \"th9.5/%s_new/outputDGammaDq2/DGammaDq2.bin\")", kernel),
"",
"",
"th <- c(2, 4, 6, 8, 9.5)",
"nerr <- rep(2, 5)",
"tsnk <- rep(48, 5)",
"Nt <- rep(24, 5)",
"",
"par.guess <- rep(1, 5)",
"",
"```",
"",
sprintf("```{r B48quarkmass%s%sextrapolatesigmatozerofinvol}", channel, kernel),
"",
"",
sprintf("savename <- \"tables/DG_quarkmass_cB48_%s_%s\"", channel, kernel),
"",
"par.guess <- rep(1, 5)",
"",
"",
sprintf("fitlist <- determineDGDq2_combine_aic(resultpathlist=list(\"/home/gross/Documents/heavymesons/data/%s/cB211.07.48_novariation/\",", channel),
sprintf("                                                       \"/home/gross/Documents/heavymesons/data/%s/cB211.07.48_strange/\", ", channel),
sprintf("                                                       \"/home/gross/Documents/heavymesons/data/%s/cB211.07.48_charm/\") ", channel),
#~ sprintf("                                                       \"/home/gross/Documents/heavymesons/data/%s/cB211.07.48_charm_strange/\"), ", channel),
"                           filenames = c(files, files, files, files, files), ",
"                           tsnk = tsnk, Nt = Nt, th = th, nerr = nerr, amin = maxAmin, savename = savename,",
"                           fitfnlist = list(fneight, fneight, fneight, fneight), ",
"                           par.guesslist = list(par.guess, par.guess, par.guess, par.guess), ",
"                           errors=c(\"stat\", \"sys\"), doplot=!(knitr::is_html_output()), ",
"                           volumetablelist = rep(\"tables/dummyvolume.csv\", 5),",
"                           numberfits = 3, legendargs=list(x=\"topright\", ncol=1, legend=c(\"un\", \"st\", \"ch\")))",
sprintf("saveRDS(object=fitlist, file=\"tables/DG_quarkmass_fitlist_cB48_%s_%s.RDS\")", channel, kernel),
"",
"```",
"### Summary",
"",
sprintf("```{r B48quarkmass%s%ssummaryfinvol}", channel, kernel),
"",
"a <- 0.079570",
"agev <- 0.079570 / 0.1973269804 # fm / hbarc = GeV^-1",
"da <- 0.00013",
"am_H <- 0.800000 # dimensionless",
"conversionfactor <- (am_H/agev)^3/2/pi",
"",
sprintf("savename <- sprintf(\"tables/DG_quarkmass_cB48_%s_%s\")", channel, kernel),
"result <- read.table(paste0(savename, \".csv\"), header=TRUE)",
"",
"result[, c(\"DGDq2gev\", \"dDGDq2gev\")] <- result[, c(\"DGDq2\", \"dDGDq2\")] * conversionfactor",
"result$q <- result$w * am_H / agev",
"result$afm <- rep(a, length(result$q))",
"result$dafm <- rep(da, length(result$q))",
"result",
"",
"for (iz in c(3, 0, 1, 2)) {",
"  for (err in c(\"stat\", \"sys\")){",
"    mask <- result$iz==iz & result$icomb==0 & result$errtype==err & result$fitno > 0",
"    try(plotwitherror(x=result$q[mask]^2+(result$fitno[mask]+1)*0.0005, y=result$DGDq2gev[mask], dy=result$dDGDq2gev[mask],",
sprintf("                      main=paste(\"differential decay rate for tsink=48, tins=36, %s, %s, \", err, \"Z\", iz), ", channel, kernel),
"                      xlab=\"q^2 [GeV^2]\", ylab=\"24 pi^3 DGamma / Dq^2 [GeV^-3]\",",
"                      ylim=c(0, max(result$DGDq2gev[mask] + result$dDGDq2gev[mask])), ",
"                      xlim=c(0, max(result$q[mask]^2+(result$fitno[mask]+1)*0.0005)), col=result$fitno[mask]))",
"    legend(x=\"topright\", col=result$fitno[mask], pch=c(1, 1, 1,",
"           legend=c(\"un\", \"st\", \"ch\"))",
"    ",
"    try(plotwitherror(x=result$q[mask]^2+(result$fitno[mask]+1)*0.0005, y=result$dDGDq2gev[mask],",
sprintf("                      main=paste(\"differential decay rate for tsink=48, tins=36, %s, %s, \", err),", channel, kernel),
"                      ylab=\"24 pi^3 d(DGamma / Dq^2) [GeV^-3]\", xlim=c(0, max(result$q[mask]^2)), col=result$fitno[mask]))",
"    legend(x=\"topleft\", col=result$fitno[mask], pch=c(1, 1, 1),",
"           legend=c(\"un\", \"st\", \"ch\"))",
"    ",
"  }",
"}",
"for(ith in th) {",
"  for (err in c(\"stat\", \"sys\")){",
"    mask <- result$th==ith & result$icomb==0 & result$errtype==err & result$fitno > 0",
"  plotwitherror(x=result$iz[mask]+0.1*(result$fitno[mask]-1), y=result$DGDq2gev[mask], dy=result$dDGDq2gev[mask],",
sprintf("                      main=paste(\"differential decay rate for tsink=48, tins=36, %s, %s, \", err, \"th\", ith), ", channel, kernel),
"                      xlab=\"Z\", ylab=\"24 pi^3 DGamma / Dq^2 [GeV^-3]\", col=result$fitno[mask], xlim=c(-1, 3.5))",
"    legend(x=\"topleft\", col=result$fitno[mask], pch=c(1, 1, 1),",
"           legend=c(\"un\", \"st\", \"ch\"))",
"  }",
"}",
"",
"dat <- readRDS(paste0(savename, \".RDS\"))",
sprintf("savename <- sprintf(\"tables/DG_quarkmass_cB48_%s_%s\")", channel, kernel),
"",
"dat$DGDq2gev <- dat$DGDq2 * conversionfactor",
"dat$dDGDq2gev <- dat$dDGDq2 * conversionfactor",
"dat$datgev <- dat$dat * conversionfactor",
"",
"saveRDS(dat, paste0(savename, \".RDS\"))",
"write.table(result, paste0(savename, \".csv\"))",
"",
"```",
file=fileDG, append=TRUE, sep="\n")
}
}



fileDG <- sprintf("%s/%s-compare-error-quarkmass-dependece.Rmd", parent, 200+6)
cat(sprintf("```{r setupcomparisonquarkmasses, include=FALSE}"), 
"knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, results = FALSE)", 
"source(\"/home/gross/Documents/heavymesons/scripts_christiane/extrapolate_sigma_templates/functions_stability_plots.R\")", 
"source(\"/home/gross/Documents/heavymesons/scripts_christiane/extrapolate_sigma_templates/calc_DGDq2.R\")", 
"source(\"/home/gross/Documents/heavymesons/scripts_christiane/extrapolate_sigma_templates/calc_DGDq2_aic.R\")", 
"library(\"hadron\")", 
"zlist <- c(3, 0, 1, 2)", 
"errlist <- c(\"stat\")", 
"sumup <-FALSE", 
"", 
"nconfig <- 300", 
"amus <- 0.01692", 
"damus <- 0.00031", 
"amuc <- 0.2368", 
"damuc <- 0.0036", 
"amud <- 0.00072", 
"amusst <- 0.019", 
"amucch <- 0.26", 
"```",
"", 
file=fileDG, append=FALSE, sep="\n")

for(kernel in c("sigmoid", "erf")){
    for(channel in c("cd", "cs")) {
        cat(
sprintf("\n\n## Decay rate %s %s", channel, kernel), 
"", 
sprintf("After the limit $\\epsilon\\to 0$ has been taken. Kernel: %s, Channel: %s", kernel, channel), 
"", 
"### first method", 
"", 
"```{r}", 
sprintf("dat <- read.table(\"~/Documents/heavymesons/data/newinput/tables/DG_quarkmass_cB48_%s_%s.csv\", header=T)", channel, kernel), 
sprintf("datboot <- readRDS(\"~/Documents/heavymesons/data/newinput/tables/DG_quarkmass_fitlist_cB48_%s_%s.RDS\")", channel, kernel), 
"datst <-dat[dat$fitno==3 & dat$errtype==\"stat\", ]", 
"datch <-dat[dat$fitno==4 & dat$errtype==\"stat\", ]", 
"datcs <-dat[dat$fitno==5 & dat$errtype==\"stat\", ]", 
"dat <- dat[dat$fitno==1 & dat$errtype==\"stat\", ]", 
"stopifnot(dat$th == datst$th)", 
"stopifnot(dat$th == datch$th)", 
"booterr <- data.frame(slopestboot_one=c(), sslopestboot_one=c(), slopechboot_one=c(), sslopechboot_one=c(),", 
"                      slopestboot_two=c(), sslopestboot_two=c(), slopechboot_two=c(), sslopechboot_two=c())", 
"for(th in c(2, 4, 6, 8, 9.5)) {", 
"  for(iz in c(0, 1, 2, 3)) {", 
"    index <- which(names(datboot) == sprintf(\"iset 0 iz %d icomb 0 tsnk 48 Nt 24 th %s nerr 2 stat\", iz, th))", 
"    datbootnv <- datboot[[index]]$fitresults[[1]]$t[, 1]", 
"    datbootst <- datboot[[index]]$fitresults[[3]]$t[, 1]", 
"    datbootch <- datboot[[index]]$fitresults[[4]]$t[, 1]", 
"    datbootcs <- datboot[[index]]$fitresults[[5]]$t[, 1]", 
"    newline <- data.frame(slopestboot_one=mean((datbootnv - datbootst)/(amus-amusst)),", 
"                          dslopestboot_one=sd((datbootnv - datbootst)/(amus-amusst)),", 
"                          slopechboot_one=mean((datbootnv - datbootch)/(amus - amucch)),", 
"                          dslopechboot_one=sd((datbootnv - datbootch)/(amus - amucch)),", 
"                          slopestboot_two=mean((datbootch - datbootcs)/(amus-amusst)),", 
"                          dslopestboot_two=sd((datbootch - datbootcs)/(amus-amusst)),", 
"                          slopechboot_two=mean((datbootst - datbootcs)/(amus - amucch)),", 
"                          dslopechboot_two=sd((datbootst - datbootcs)/(amus - amucch)))", 
"    booterr <- rbind(booterr, newline)", 
"    ", 
"  }", 
"}", 
"", 
"errordecayquarkmassone <- data.frame(th=dat$th, Z=dat$iz, mean=dat$DGDq2, sd=dat$dDGDq2, ", 
"                                     slopest_one = (dat$DGDq2-datst$DGDq2)/(amus - amusst), ", 
"                                     slopech_one = (dat$DGDq2-datch$DGDq2)/(amus - amucch), ", 
"                                     slopest_two = (datch$DGDq2-datcs$DGDq2)/(amus - amusst), ", 
"                                     slopech_two = (datst$DGDq2-datcs$DGDq2)/(amus - amucch))", 
"errordecayquarkmassone <- cbind(errordecayquarkmassone, booterr)", 
"errordecayquarkmassone$sdst_one = abs(errordecayquarkmassone$slopest_one) * damus", 
"errordecayquarkmassone$sdch_one = abs(errordecayquarkmassone$slopech_one) * damuc", 
"errordecayquarkmassone$sdstboot_one = abs(errordecayquarkmassone$slopestboot_one) * damus", 
"errordecayquarkmassone$sdchboot_one = abs(errordecayquarkmassone$slopechboot_one) * damuc", 
"errordecayquarkmassone$sdsdstboot_one = abs(errordecayquarkmassone$dslopestboot_one) * damus", 
"errordecayquarkmassone$sdsdchboot_one = abs(errordecayquarkmassone$dslopechboot_one) * damuc", 
"errordecayquarkmassone$sdquark_one = sqrt(errordecayquarkmassone$sdst_one^2 + errordecayquarkmassone$sdch_one^2)", 
"errordecayquarkmassone$sdquarkboot_one = sqrt(errordecayquarkmassone$sdstboot_one^2 + errordecayquarkmassone$sdchboot_one^2)", 
"errordecayquarkmassone$sdsdquarkboot_one = (sqrt((errordecayquarkmassone$sdstboot_one * errordecayquarkmassone$sdsdchboot_one)^2 + ", 
"                                                   (errordecayquarkmassone$sdchboot_one * errordecayquarkmassone$sdsdstboot_one)^2) ", 
"                                            / sqrt(errordecayquarkmassone$sdstboot_one^2 + errordecayquarkmassone$sdchboot_one^2))", 
"errordecayquarkmassone$sdst_two = abs(errordecayquarkmassone$slopest_two) * damus", 
"errordecayquarkmassone$sdch_two = abs(errordecayquarkmassone$slopech_two) * damuc", 
"errordecayquarkmassone$sdstboot_two = abs(errordecayquarkmassone$slopestboot_two) * damus", 
"errordecayquarkmassone$sdchboot_two = abs(errordecayquarkmassone$slopechboot_two) * damuc", 
"errordecayquarkmassone$sdsdstboot_two = abs(errordecayquarkmassone$dslopestboot_two) * damus", 
"errordecayquarkmassone$sdsdchboot_two = abs(errordecayquarkmassone$dslopechboot_two) * damuc", 
"errordecayquarkmassone$sdquark_two = sqrt(errordecayquarkmassone$sdst_two^2 + errordecayquarkmassone$sdch_two^2)", 
"errordecayquarkmassone$sdquarkboot_two = sqrt(errordecayquarkmassone$sdstboot_two^2 + errordecayquarkmassone$sdchboot_two^2)", 
"errordecayquarkmassone$sdsdquarkboot_two = (sqrt((errordecayquarkmassone$sdstboot_two * errordecayquarkmassone$sdsdchboot_two)^2 + ", 
"                                                   (errordecayquarkmassone$sdchboot_two * errordecayquarkmassone$sdsdstboot_two)^2) ", 
"                                            / sqrt(errordecayquarkmassone$sdstboot_two^2 + errordecayquarkmassone$sdchboot_two^2))", 
"# knitr::kable(errordecayquarkmassone, digits=5)", 
"errordecayquarkmassone", 
"write.table(x=errordecayquarkmassone, ", 
sprintf("            file = \"~/Documents/heavymesons/data/newinput/tables/decayquarkmassdependence_methodone_%s_%s.csv\")", channel, kernel), 
"```", 
"```{r, eval=FALSE}", 
"for(Z in c(0, 1, 2, 3)) {", 
"  mask <- errordecayquarkmassone$Z==Z", 
"  plotwitherror(x=errordecayquarkmassone$th[mask], y=rep(0, 5), dy=errordecayquarkmassone$dslopestboot_one[mask], ", 
"                main=paste(\"difference slopes strange, Z=\", Z), xlab=\"th\", ylab=\"difference slope strange\",", 
"                ylim=max(errordecayquarkmassone$dslopestboot_one[mask])*c(-1, 1))", 
"  plotwitherror(x=errordecayquarkmassone$th[mask], ", 
"                y=abs(errordecayquarkmassone$slopestboot_two[mask]) - abs(errordecayquarkmassone$slopestboot_one[mask]),", 
"                dy=errordecayquarkmassone$dslopestboot_two[mask], ", 
"                pch=2, col=2, rep=TRUE)", 
"  legend(x=\"topright\", legend=c(\"low charm mass\", \"high charm mass\"), col=c(1, 2), pch=c(1, 2))", 
"  plotwitherror(x=errordecayquarkmassone$th[mask], y=rep(0, 5), dy=errordecayquarkmassone$dslopechboot_one[mask], ", 
"                main=paste(\"difference slopes charm, Z=\", Z), xlab=\"th\", ylab=\"slope charm\",", 
"                ylim=max(errordecayquarkmassone$dslopechboot_one[mask])*c(-1, 1))", 
"  plotwitherror(x=errordecayquarkmassone$th[mask], ", 
"                y=abs(errordecayquarkmassone$slopechboot_two[mask]) - abs(errordecayquarkmassone$slopechboot_one[mask]),", 
"                dy=errordecayquarkmassone$dslopechboot_two[mask], ", 
"                pch=2, col=2, rep=TRUE)", 
"  legend(x=\"topright\", legend=c(\"low strange mass\", \"high strange mass\"), col=c(1, 2), pch=c(1, 2))", 
"}", 
"```", 
"", 
"### second method", 
"", 
"```{r}", 
sprintf("dat <- read.table(\"~/Documents/heavymesons/data/newinput/tables/DG_quarkmass_cB48_%s_%s.csv\", header=T)", channel, kernel), 
"datvar <-dat[dat$fitno==3 & dat$errtype==\"stat\", ]", 
"dat <- dat[dat$fitno==1 & dat$errtype==\"stat\", ]", 
"stopifnot(dat$th == datvar$th)", 
"errordecayquarkmasstwo <- data.frame(th=dat$th, Z=dat$iz, mean=dat$DGDq2, sd=dat$dDGDq2, sdvar=datvar$dDGDq2, sdquark=sqrt(datvar$dDGDq2^2-dat$dDGDq2^2))", 
"knitr::kable(errordecayquarkmasstwo, digits=5)", 
"write.table(x=errordecayquarkmasstwo, ", 
sprintf("            file = \"~/Documents/heavymesons/data/newinput/tables/decayquarkmassdependence_methodtwo_%s_%s.csv\")", channel, kernel), 
"```", 
"", 
"",  
"### comparison absolute",
"", 
"```{r}", 
"comparedecaymass <- data.frame(th=errordecayquarkmasstwo$th, Z=errordecayquarkmasstwo$Z, mean=errordecayquarkmasstwo$mean, ", 
"                               sd=errordecayquarkmasstwo$sd, ", 
"                               erroronelow =errordecayquarkmassone$sdquark_one, ", 
"                               erroronehigh =errordecayquarkmassone$sdquark_two, ", 
"                               errorerroronelow =errordecayquarkmassone$sdsdquarkboot_one, ", 
"                               errorerroronehigh =errordecayquarkmassone$sdsdquarkboot_two, ", 
"                               errortwo=errordecayquarkmasstwo$sdquark)", 
"knitr::kable(comparedecaymass, digits=5, format.args=list(scientific=F))", 
"for(iz in c(0, 1, 2, 3)) {", 
"  mask <- comparedecaymass$Z==iz", 
"  plotwitherror(x=comparedecaymass$th[mask], y=comparedecaymass$erroronelow[mask],", 
"                dy=comparedecaymass$errorerroronelow[mask], ", 
"                xlab=\"th\", ylab=\"sd_quark\",", 
"                main=paste(\"absolute value of error from quark masses, Z\", iz),", 
"                ylim=c(0, max(comparedecaymass$erroronelow[mask], comparedecaymass$erroronehigh[mask], na.omit(comparedecaymass$errortwo[mask]))))", 
#~ "  plotwitherror(x=comparedecaymass$th[mask], y=comparedecaymass$erroronehigh[mask],", 
#~ "                dy=comparedecaymass$errorerroronehigh[mask], col=3, pch=3, rep=TRUE)", 
#~ "  points(x=comparedecaymass$th[mask], y=comparedecaymass$errortwo[mask], col=2, pch=2)", 
#~ "  legend(x=\"topleft\", legend=c(\"met. 1 low\", \"met. 1 high\", \"met. 2\"), col=c(1, 3, 2), pch=c(1, 3, 2))", 
"  legend(x=\"topleft\", legend=c(\"error\"), col=c(1, 3, 2), pch=c(1, 3, 2))", 
"}", 
"```", 

"\n### comparison relative to statistical error\n",

"```{r}", 
"for(iz in c(0, 1, 2, 3)) {", 
"  mask <- comparedecaymass$Z==iz", 
"  plotwitherror(x=comparedecaymass$th[mask], y=comparedecaymass$erroronelow[mask]/comparedecaymass$sd[mask],", 
"                dy=comparedecaymass$errorerroronelow[mask]/comparedecaymass$sd[mask], ", 
"       xlab=\"th\", ylab=\"sd_quark\", ", 
"       main=paste(\"relative size of error from quark mass to statistical error, Z\", iz),", 
"       ylim=c(0, max(comparedecaymass$erroronelow[mask]/comparedecaymass$sd[mask], ", 
"                     comparedecaymass$erroronehigh[mask]/comparedecaymass$sd[mask],", 
"                     na.omit(comparedecaymass$errortwo[mask]/comparedecaymass$sd[mask]))))", 
#~ "  plotwitherror(x=comparedecaymass$th[mask], y=comparedecaymass$erroronehigh[mask]/comparedecaymass$sd[mask],", 
#~ "                dy=comparedecaymass$errorerroronehigh[mask]/comparedecaymass$sd[mask], col=3, pch=3, rep=TRUE)", 
#~ "  points(x=comparedecaymass$th[mask], y=comparedecaymass$errortwo[mask]/comparedecaymass$sd[mask], col=2, pch=2)", 
#~ "  legend(x=\"topleft\", legend=c(\"met. 1 low\", \"met. 1 high\", \"met. 2\"), col=c(1, 3, 2), pch=c(1, 3, 2))", 
"  legend(x=\"topleft\", legend=c(\"diff\"), col=c(1, 3, 2), pch=c(1, 3, 2))", 

sprintf("png(\"~/sciebo/presentations/lattice2024/ugly/quarkmassrelative%s%s.png\")", channel, kernel), 
"mask <- comparedecaymass$Z!=3", 
"plotwitherror(x=(comparedecaymass$th[mask]*0.0934217028332725)^2, y=comparedecaymass$erroronelow[mask]/comparedecaymass$sd[mask]*100,", 
"              dy=comparedecaymass$errorerroronelow[mask]/comparedecaymass$sd[mask]*100, ", 
"              xlab=paste(\"q^2 [GeV^2]\"), ylab=\"mass error / statistical error  [%]\", ", 
"              main=\"\",", 
"              ylim=c(0, max(comparedecaymass$erroronelow[mask]/comparedecaymass$sd[mask]))*100,", 
"              col=comparedecaymass$Z+1, pch=comparedecaymass$Z+1,", 
"              xlim=c(-0.1, 0.8))", 
"legend(x=\"topleft\", title=\"Z\", legend=seq(0, 2), col=c(1, 2, 3), pch=c(1, 2, 3))", 
"dev.off()
}", 
"```",

file=fileDG, append=TRUE, sep="\n")
}
}
