parent <- "~/Documents/heavymesons/data/newinput"
folders <- c("cB211.07.64", "cB211.07.96", "cC211.06.80", "cD211.054.96", "cE211.044.112", "cB211.07.48_300", "cB211.07.48_400", "cB211.07.64_48_36")
nameshort <- c("B64", "B96", "C80", "D96", "E112", "B48_300", "B48_400", "B64_48_36")
subfolders  <- c("th1", "th2", "th3", "th4", "th5", "th6", "th7", "th8", "th9", "th9.5")

infos <- read.table("parameters_input_files.csv", row.names=1, header=TRUE, sep=",", comment.char = "#")
#~ print(infos)
names(infos)


## TODO: write volume effects



fileDG <- sprintf("%s/%s-pull-factor-DGDq2.Rmd", parent, 4*length(folders)+6)
fileDM <- sprintf("%s/%s-pull-factor-DMDq2.Rmd", parent, 4*length(folders)+6)

cat(
"```{r setupsummaryvolume, include=FALSE}", 
"knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, results = FALSE)", 
"source(\"/home/gross/Documents/heavymesons/scripts_christiane/extrapolate_sigma_templates/functions_stability_plots.R\")", 
"source(\"/home/gross/Documents/heavymesons/scripts_christiane/extrapolate_sigma_templates/calc_DGDq2.R\")", 
"source(\"/home/gross/Documents/heavymesons/scripts_christiane/extrapolate_sigma_templates/functions_pull_factor.R\")", 
"library(\"hadron\")", 
"zlist <- c(3, 0, 1, 2)", 
"errlist <- c(\"stat\")", 
"sumup <-FALSE", 
"erf <- function(x) 2 * pnorm(x * sqrt(2)) - 1", 
"```\n",
file=fileDG, append=F, sep="\n")


for(kernel in c("sigmoid", "erf")){
    for(channel in c("cd", "cs")) {
    cat(
sprintf("## %s %s", channel, kernel), 
"", 
sprintf("```{r epsilon_volume_%s_%s}", channel, kernel), 
"fnlin <- function(par, x, boot.R, ...) par[1] + par[2] * x", 
"fncon <- function(par, x, boot.R, ...) par[1]", 
"", 
"fitfn <- fnlin", 
"par.guess <- c(1, 1)", 
"comment <- \"linear\"", 
"", 
"res <- data.frame(th=c(), epsilon=c(), iz=c(), lim=c(), dlim=c(), sloipe=c(), dslope=c(), chi=c(), ", 
"                  ratio64=c(), dratio64=c(), ratio5644=c(), dratio5644=c(), ratio4836=c(), dratio4836=c(),", 
"                  volcorr=c(), dvolcorr=c())", 
"listvolcorr <- list()", 
"", 
"pcol <- col2rgb(\"gray\", alpha=TRUE)/255 ", 
"pcol[4] <- 0.65", 
"pcol <- rgb(red=pcol[1],green=pcol[2],blue=pcol[3],alpha=pcol[4])", 
"", 
"confcounter <- 1", 
"epsilons <- seq(1, 19)-1 ## go to C-style indexing for reading in", 
"", 
"", 
"", 
"for(th in c(seq(1, 9), 9.5)) {", 
"  listvolcorr <- list(fitresult=list(), interpolate=list())", 
"  enslist <- list()",
sprintf("  enslist$B48 <- read_in_DGDq2(resultpath=sprintf(\"~/Documents/heavymesons/data/%s/cB211.07.48_400/th%%s/%s_new/outputDGammaDq2/\", as.character(th)), filename=\"DGammaDq2.bin\")", channel, kernel), 
sprintf("  enslist$B64_56_44 <- read_in_DGDq2(resultpath=sprintf(\"~/Documents/heavymesons/data/%s/cB211.07.64/th%%s/%s_new/outputDGammaDq2/\", as.character(th)), filename=\"DGammaDq2.bin\")", channel, kernel), 
sprintf("  enslist$B64_48_36 <- read_in_DGDq2(resultpath=sprintf(\"~/Documents/heavymesons/data/%s/cB211.07.64_48_36/th%%s/%s_new/outputDGammaDq2/\", as.character(th)), filename=\"DGammaDq2.bin\")", channel, kernel), 
sprintf("  enslist$B96 <- read_in_DGDq2(resultpath=sprintf(\"~/Documents/heavymesons/data/%s/cB211.07.96/th%%s/%s_new/outputDGammaDq2/\", as.character(th)), filename=\"DGammaDq2.bin\")", channel, kernel), 
"  enslist$L <- c(48, 64, 64, 96)",
"  for (icomb in c(0)) {", 
"    for(iz in zlist) {",  
"      for (epsilon in epsilons){", 
"        ", 
"        title <- sprintf(\"th%s iz %d epsilon %d\", th, iz, epsilon)", 
"        print(title)", 
"        bsamples <- array(NA, dim=c(1000, length(enslist)-1))", 
"        y <- c()", 
"        dy <- c()", 
"        x <- c()", 
"        for (index in seq(1, length(enslist)-1)) {", 
"          tmp <- extractdata(data=enslist[[index]], iz=iz, epsilons = epsilon, icomb=icomb)", 
"          y[index] <- tmp$DGammamean", 
"          dy[index] <- tmp$dDGamma", 
"          bsamples[, index] <- tmp$boot", 
"        }", 
"        x <- enslist$L", 
"        fitresult <- try(bootstrap.nlsfit(x=x, y=y, bsamples=bsamples, fn=fitfn, par.guess=par.guess))", 
"        ", 
"        if(!inherits(x = fitresult, what=\"try-error\")){", 
"          plot(fitresult,", 
sprintf("               main=paste(\"%s %s diff. decay rate epsilon\", epsilon, \", z =\", iz, \"th\", th),", channel, kernel), 
"               xlab=\"L\", ylab=\"24 pi^3 DGamma / Dq^2 [GeV^-3]\", xaxt=\"n\")",
"          plotwitherror(x=x[3:4], y=y[3:4], dy=dy[3:4], rep=T, pch=1)", 
"          ratio64 <- bsamples[, 2] / bsamples[, 3]", 
"          ratio5644 <- bsamples[, 3] / bsamples[, 4]", 
"          ratio4836 <- bsamples[, 1] / bsamples[, 2]", 
"          VCDE <- predict(fitresult, x = 68.5)", 
"          listvolcorr[[\"interpolate\"]][[paste0(\"icomb\", icomb, \"iz\", iz, \"epsilon\", epsilon)]] <- VCDE", 
"          listvolcorr[[\"fitresult\"]][[paste0(\"icomb\", icomb, \"iz\", iz, \"epsilon\", epsilon)]] <- fitresult", 
"          newline <- data.frame(th=th, epsilon=epsilon, iz=iz,", 
"                                lim=fitresult$t0[1], dlim=fitresult$se[1],", 
"                                slope=fitresult$t0[2], dslope=fitresult$se[2],", 
"                                chi=fitresult$chisqr / fitresult$dof,", 
"                                ratio64 = mean(ratio64), dratio64=sd(ratio64),", 
"                                ratio5644 = mean(ratio5644), dratio5644=sd(ratio5644),", 
"                                ratio4836 = mean(ratio4836), dratio4836=sd(ratio4836),", 
"                                volcorr=VCDE$val, dvolcorr=VCDE$err)", 
"          res <- rbind(res, newline)", 
"        } else {", 
"          plotwitherror(x=x[3:4], y=y[3:4], dy=dy[3:4],", 
sprintf("                        main=paste(\"%s %s diff. decay rate epsilon\", epsilon, \", z =\", iz, \"th\", th),", channel, kernel), 
"                        xlab=\"L\", ylab=\"24 pi^3 DGamma / Dq^2 [GeV^-3]\",", 
"                        ylim=c(min(y-dy),", 
"                               max(y+dy)),", 
"                        xlim=c(1/96, 1/48), xaxt=\"n\")", 
"        }", 
"        axis(side=1, at=c(48, 64, 96), label=c(\"48\", \"64\", \"96\"))", 
"        legend(x=\"topleft\", legend=c(\"56, 44\", \"48, 36\", \"pred.\"), col=c(1, 2, 4), pch=c(1, 1, 2), title=c(\"tsnk, tj\"))", 
"        plotwitherror(x=x[1:2], y=y[1:2], dy=dy[1:2],", 
"                      rep=TRUE, col=2, pch=1, lwd=1.2)", 
"        plotwitherror(x=VCDE$x, y=VCDE$val, dy=VCDE$err,", 
"                      rep=TRUE, col=4, pch=1, lwd=1.2)", 
"        ", 
"      }", 
"    }", 
"  }", 
"  listvolcorr$neps <- length(epsilons)", 
"  listvolcorr$epsilons <- enslist[[1]][[2]]$epsilons[epsilons+1]", 
"  listvolcorr$Z <- zlist", 
"  print(names(listvolcorr))", 
sprintf("  saveRDS(object=listvolcorr, file=sprintf(\"~/Documents/heavymesons/data/newinput/tables/volume_interpolations/DG_vol_B_th%%s_%s_%s.RDS\", as.character(th)))", channel, kernel), 
"  rm(enslist)",
"}", 
"```\n",
file=fileDG, append=T, sep="\n")
}
}
    
fileDG <- sprintf("%s/%s-volume-errors-DGDq2.Rmd", parent, 4*length(folders)+7)
fileDM <- sprintf("%s/%s-volume-errors-DMDq2.Rmd", parent, 4*length(folders)+7)

cat(
"```{r setupsummaryvolume, include=FALSE}", 
"knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, results = FALSE)", 
"source(\"/home/gross/Documents/heavymesons/scripts_christiane/extrapolate_sigma_templates/functions_stability_plots.R\")", 
"source(\"/home/gross/Documents/heavymesons/scripts_christiane/extrapolate_sigma_templates/calc_DGDq2.R\")", 
"source(\"/home/gross/Documents/heavymesons/scripts_christiane/extrapolate_sigma_templates/functions_pull_factor.R\")", 
"library(\"hadron\")", 
"zlist <- c(3, 0, 1, 2)", 
"errlist <- c(\"stat\")", 
"sumup <-FALSE", 
"erf <- function(x) 2 * pnorm(x * sqrt(2)) - 1", 
"```\n",
file=fileDG, append=F, sep="\n")


for(kernel in c("sigmoid", "erf")){
    for(channel in c("cd", "cs")) {
    cat(
sprintf("## %s %s\n\n", channel, kernel),
sprintf("```{r volerrs%s%s}", channel, kernel),
"filenames <- rep(\"DGammaDq2.bin\", 10)", 
sprintf("resultpathB96 <- c(\"~/Documents/heavymesons/data/%s/cB211.07.96/th1/%s_new/outputDGammaDq2/\",", channel, kernel), 
sprintf("                   \"~/Documents/heavymesons/data/%s/cB211.07.96/th2/%s_new/outputDGammaDq2/\",", channel, kernel), 
sprintf("                   \"~/Documents/heavymesons/data/%s/cB211.07.96/th3/%s_new/outputDGammaDq2/\",", channel, kernel), 
sprintf("                   \"~/Documents/heavymesons/data/%s/cB211.07.96/th4/%s_new/outputDGammaDq2/\",", channel, kernel), 
sprintf("                   \"~/Documents/heavymesons/data/%s/cB211.07.96/th5/%s_new/outputDGammaDq2/\",", channel, kernel), 
sprintf("                   \"~/Documents/heavymesons/data/%s/cB211.07.96/th6/%s_new/outputDGammaDq2/\",", channel, kernel), 
sprintf("                   \"~/Documents/heavymesons/data/%s/cB211.07.96/th7/%s_new/outputDGammaDq2/\",", channel, kernel), 
sprintf("                   \"~/Documents/heavymesons/data/%s/cB211.07.96/th8/%s_new/outputDGammaDq2/\",", channel, kernel), 
sprintf("                   \"~/Documents/heavymesons/data/%s/cB211.07.96/th9/%s_new/outputDGammaDq2/\",", channel, kernel), 
sprintf("                   \"~/Documents/heavymesons/data/%s/cB211.07.96/th9.5/%s_new/outputDGammaDq2/\")", channel, kernel), 
"", 
sprintf("resultpathB64 <- c(\"~/Documents/heavymesons/data/%s/cB211.07.64/th1/%s_new/outputDGammaDq2/\",", channel, kernel), 
sprintf("                   \"~/Documents/heavymesons/data/%s/cB211.07.64/th2/%s_new/outputDGammaDq2/\",", channel, kernel), 
sprintf("                   \"~/Documents/heavymesons/data/%s/cB211.07.64/th3/%s_new/outputDGammaDq2/\",", channel, kernel), 
sprintf("                   \"~/Documents/heavymesons/data/%s/cB211.07.64/th4/%s_new/outputDGammaDq2/\",", channel, kernel), 
sprintf("                   \"~/Documents/heavymesons/data/%s/cB211.07.64/th5/%s_new/outputDGammaDq2/\",", channel, kernel), 
sprintf("                   \"~/Documents/heavymesons/data/%s/cB211.07.64/th6/%s_new/outputDGammaDq2/\",", channel, kernel), 
sprintf("                   \"~/Documents/heavymesons/data/%s/cB211.07.64/th7/%s_new/outputDGammaDq2/\",", channel, kernel), 
sprintf("                   \"~/Documents/heavymesons/data/%s/cB211.07.64/th8/%s_new/outputDGammaDq2/\",", channel, kernel), 
sprintf("                   \"~/Documents/heavymesons/data/%s/cB211.07.64/th9/%s_new/outputDGammaDq2/\",", channel, kernel), 
sprintf("                   \"~/Documents/heavymesons/data/%s/cB211.07.64/th9.5/%s_new/outputDGammaDq2/\")", channel, kernel), 
"", 
sprintf("filenamesinterpolated <- c(\"DG_vol_B_th1_%s_%s.RDS\",", channel, kernel), 
sprintf("                           \"DG_vol_B_th2_%s_%s.RDS\",", channel, kernel), 
sprintf("                           \"DG_vol_B_th3_%s_%s.RDS\",", channel, kernel), 
sprintf("                           \"DG_vol_B_th4_%s_%s.RDS\",", channel, kernel), 
sprintf("                           \"DG_vol_B_th5_%s_%s.RDS\",", channel, kernel), 
sprintf("                           \"DG_vol_B_th6_%s_%s.RDS\",", channel, kernel), 
sprintf("                           \"DG_vol_B_th7_%s_%s.RDS\",", channel, kernel), 
sprintf("                           \"DG_vol_B_th8_%s_%s.RDS\",", channel, kernel), 
sprintf("                           \"DG_vol_B_th9_%s_%s.RDS\",", channel, kernel), 
sprintf("                           \"DG_vol_B_th9.5_%s_%s.RDS\")", channel, kernel), 
"", 
"resultpathinterpolated <- rep(\"~/Documents/heavymesons/data/newinput/tables/volume_interpolations/\", 10)", 
"", 
"nerr <- rep(2, 10)", 
"L96 <- rep(96, 10)", 
"L64 <- rep(64, 10)", 
"Linter <- rep(68.5, 10)", 
"th <- c(seq(1, 9), 9.5)", 
"```\n",
"\n### pull factor from interpolated matching volume\n",
sprintf("```{r volerrmatchings%s%s}\n", channel, kernel),
"", 
"dat1 <- determinesyserrfinitevolumeextrapolated(filenames1 = filenames, ", 
"                                        resultpath1 = resultpathB96, ", 
"                                        nerr1 = nerr, L1 = L96, ", 
"                                        resultpath2 = resultpathinterpolated, ", 
"                                        filenames2 = filenamesinterpolated, nerr2 = nerr, L2 = Linter, th = th, ", 
sprintf("                                        savename = \"~/Documents/heavymesons/data/newinput/tables/volume_interpolations/trypullfactor_%s_%s\")", channel, kernel), 
"print(dat1)", 
"", 
"```\n",
"\n### pull factor from B64\n",
sprintf("```{r volerrsB64%s%s}\n", channel, kernel),
"dat2 <- determinesyserrfinitevolume(filenames1 = filenames, ", 
"                                        resultpath1 = resultpathB96, ", 
"                                        nerr1 = nerr, L1 = L96, ", 
"                                        resultpath2 = resultpathB64, ", 
"                                        filenames2 = filenames, nerr2 = nerr, L2 = L64, th = th, ", 
sprintf("                                        savename = \"~/Documents/heavymesons/data/newinput/tables/volume_interpolations/tryB64factor_%s_%s\")", channel, kernel), 
"print(dat2)", 
"", 
"```", 
"\n### comparison pull factors\n",
"```{r}", 
"for(iz in c(0, 1, 2, 3)) {", 
"plot(x=seq(1, length(dat1$P[dat1$iz==iz])), y=dat1$P[dat1$iz==iz],",
"     pch=1, col=1, xlab=\"index\", ylab=\"P\", main=paste(\"Z\", iz),",
"     ylim=range(na.omit(dat2$P[dat2$iz==iz], dat1$P[dat1$iz==iz])))", 
"points(x=seq(1, length(dat2$P[dat2$iz==iz])), y=dat2$P[dat2$iz==iz], col=2, pch=2)", 
"legend(x=\"topleft\", legend=c(\"inter\", \"B64\"), horiz=T, col=c(1, 2), pch=c(1, 2))",

"}", 
"```\n",
file=fileDG, append=T, sep="\n")
}
}

print(warnings())
