parent <- "~/Documents/heavymesons/data/newinput"
folders <- c("cB211.07.64", "cB211.07.96", "cC211.06.80", "cD211.054.96", "cE211.044.112", "cB211.07.48_300", "cB211.07.48_400", "cB211.07.64_48_36")
nameshort <- c("B64", "B96", "C80", "D96", "E112", "B48_300", "B48_400", "B64_48_36")
#~ folders <- c("cB211.07.48_400", "cB211.07.64_48_36")
#~ nameshort <- c("B48_400", "B64_48_36")
subfolders  <- c("th1", "th2", "th3", "th4", "th5", "th6", "th7", "th8", "th9", "th9.5")

infos <- read.table("parameters_input_files.csv", row.names=1, header=TRUE, sep=",", comment.char = "#")
#~ print(infos)
names(infos)


fileDG <- sprintf("%s/%s-extrapoletesigma-aic-DGDq2.Rmd", parent, 4*length(folders)+9)
fileDM <- sprintf("%s/%s-extrapoletesigma-aic-DMDq2.Rmd", parent, 4*length(folders)+9)
cat(
"---",
"output:",
"  html_document: default",
"  pdf_document: default",
"---",
"",
"```{r setupextrapolate, include=FALSE}",
"knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, results = FALSE)",
"source(\"/home/gross/Documents/heavymesons/scripts_christiane/extrapolate_sigma_templates/functions_stability_plots.R\")",
"source(\"/home/gross/Documents/heavymesons/scripts_christiane/extrapolate_sigma_templates/calc_DGDq2.R\")",
"source(\"/home/gross/Documents/heavymesons/scripts_christiane/extrapolate_sigma_templates/calc_DGDq2_aic.R\")",
"library(\"hadron\")",
"```",
"",
"# Extrapolation $\\sigma \\to 0$\n",
file=fileDG, append=FALSE, sep="\n")
system(sprintf("cp %s %s", fileDG, fileDM))


for(channel in c("cd", "cs")) {
    cat(
"",
sprintf("```{r %ssetupextrapolationaic}", channel),
"fneight <- function(par, x, boot.R, ...) par[1] + par[2] * x**2 + par[3] * x**4 + par[4] * x**6 + par[5] * x**8",
"fnsix <- function(par, x, boot.R, ...) par[1] + par[2] * x**2 + par[3] * x**4 + par[4] * x**6",
"",
"maxAmin <- 1",
"",
"filessigmoid <- c(\"th1/sigmoid_new/outputDGammaDq2/DGammaDq2.bin\",",
"           \"th2/sigmoid_new/outputDGammaDq2/DGammaDq2.bin\",",
"           \"th3/sigmoid_new/outputDGammaDq2/DGammaDq2.bin\",",
"           \"th4/sigmoid_new/outputDGammaDq2/DGammaDq2.bin\",",
"           \"th5/sigmoid_new/outputDGammaDq2/DGammaDq2.bin\",",
"           \"th6/sigmoid_new/outputDGammaDq2/DGammaDq2.bin\",",
"           \"th7/sigmoid_new/outputDGammaDq2/DGammaDq2.bin\",",
"           \"th8/sigmoid_new/outputDGammaDq2/DGammaDq2.bin\",",
"           \"th9/sigmoid_new/outputDGammaDq2/DGammaDq2.bin\",",
"           \"th9.5/sigmoid_new/outputDGammaDq2/DGammaDq2.bin\")",
"",
"fileserf <- c(\"th1/erf_new/outputDGammaDq2/DGammaDq2.bin\",",
"           \"th2/erf_new/outputDGammaDq2/DGammaDq2.bin\",",
"           \"th3/erf_new/outputDGammaDq2/DGammaDq2.bin\",",
"           \"th4/erf_new/outputDGammaDq2/DGammaDq2.bin\",",
"           \"th5/erf_new/outputDGammaDq2/DGammaDq2.bin\",",
"           \"th6/erf_new/outputDGammaDq2/DGammaDq2.bin\",",
"           \"th7/erf_new/outputDGammaDq2/DGammaDq2.bin\",",
"           \"th8/erf_new/outputDGammaDq2/DGammaDq2.bin\",",
"           \"th9/erf_new/outputDGammaDq2/DGammaDq2.bin\",",
"           \"th9.5/erf_new/outputDGammaDq2/DGammaDq2.bin\")",
"",
"th <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 9.5)",
"nerr <- rep(2, 10)",
"",
"par.guess <- rep(1, 5)",
"",
"```",
file=fileDG, append=TRUE, sep="\n")
#~         for (i in seq_along(folders)) {
    for (i in c(1:5, 7)) {
        folder <- folders[i]
            ensinfos <- infos[folder]
        cat(
        "",
        sprintf("## %s %s", nameshort[i], channel),
        "### Extrapolations",
        "",
        sprintf("```{r %s%sextrapolatesigmatozerofinvolaic}", nameshort[i], channel),
        "",
        sprintf("tsnk <- rep(%d, 10)", ensinfos["tsink", ]),
        sprintf("Nt <- rep(%d, 10)", ensinfos["Nt", ]),
        "",
        sprintf("savename <- sprintf(\"tables/DG_complete_c%s_%s_finvol_aic\")", nameshort[i], channel),
        "",
        "",
        "",
sprintf("mine <- determineDGDq2_combine_aic(resultpathlist=list(\"/home/gross/Documents/heavymesons/data/%s/%s/\",", channel, folder), 
sprintf("                                                       \"/home/gross/Documents/heavymesons/data/%s/%s/\"),", channel, folder), 
"                           filenames = c(filessigmoid, fileserf), ", 
"                           tsnk = tsnk, Nt = Nt, th = th, nerr = nerr, amin = maxAmin, savename = savename,", 
"                           fitfnlist = list(fnsix, fnsix), ", 
"                           par.guesslist = list(rep(1, 4), rep(1, 4)), ", 
"                           errors=c(\"stat\", \"sys\", \"vol\", \"tot\"), doplot=!(knitr::is_html_output()), ", 
sprintf("                           volumetablelist = c(\"tables/volume_interpolations/tryB64factor_%s_sigmoid.csv\",", channel),
sprintf("                                               \"tables/volume_interpolations/tryB64factor_%s_erf.csv\"),", channel),
"                           legendargs=list(legend=c(\"sigmoid 6\", \"erf 6\"), x=\"topright\"),",
"                           numberfits = 2, neps=15)",
#~         sprintf("determineDGDq2_all(resultpath = \"/home/gross/Documents/heavymesons/data/%s/%s/\", filenames = files, ", channel, folder),
#~         "        tsnk = tsnk, Nt = Nt, th = th, nerr = nerr, amin = maxAmin, savename = savename,",
#~         "        fitfn = fneight, par.guess = par.guess, errors=c(\"stat\", \"sys\", \"vol\", \"tot\"),",
#~             "        fitfn = fneight, par.guess = par.guess, errors=c(\"stat\", \"sys\"),",
#~         sprintf("        volumetable=\"tables/volume_interpolations/tryB64factor_%s_%s.csv\", doplot=!(knitr::is_html_output()),", channel, kernel),
#~         "        neps=19)",
        "",
        "```",
        "",
        "",
        "",
        "### Summary",
        "",
        sprintf("```{r %s%ssummaryfinvolaic}", nameshort[i], channel),
        "",
        sprintf("a <- %f", ensinfos["afm", ]),
        sprintf("agev <- %f / 0.1973269804 # fm / hbarc = GeV^-1", ensinfos["afm", ]),
        "da <- 0.00013",
        sprintf("am_H <- %f # dimensionless", ensinfos["ameff_calc", ]),
        "conversionfactor <- (am_H/agev)^3/2/pi",
        "",
        sprintf("savename <- sprintf(\"tables/DG_complete_c%s_%s_finvol_aic\")", nameshort[i], channel),
        "result <- read.table(paste0(savename, \".csv\"), header=TRUE)",
        "",
        "result[, c(\"DGDq2gev\", \"dDGDq2gev\")] <- result[, c(\"DGDq2\", \"dDGDq2\")] * conversionfactor",
        "result$q <- result$w * am_H / agev",
        "result$afm <- rep(a, length(result$q))",
        "result$dafm <- rep(da, length(result$q))",
        "",
        "for (iz in c(3, 0, 1, 2)) {",
        "  for (err in c(\"stat\", \"sys\", \"vol\", \"tot\")){",
#~             "  for (err in c(\"stat\", \"sys\")){",
        "    mask <- result$iz==iz & result$icomb==0 & result$errtype==err & result$fitno == -1",
        "    try(plotwitherror(x=result$q[mask]^2, y=result$DGDq2gev[mask], dy=result$dDGDq2gev[mask],",
        sprintf("                  main=paste(\"differential decay rate for tsink=%d, tins=%d, aic, %s, \", err, \"Z\", iz), ", ensinfos["tsink", ], ensinfos["tj", ], channel),
        "                  xlab=\"q^2 [GeV^2]\", ylab=\"24 pi^3 DGamma / Dq^2 [GeV^-3]\",",
        "                  ylim=c(0, max(result$DGDq2gev[mask] + result$dDGDq2gev[mask])), xlim=c(0, max(result$q[mask]^2))))",
        "    ",
        "    try(plotwitherror(x=result$q[mask]^2, y=result$dDGDq2gev",
        "                  [mask],",
        sprintf("                  main=paste(\"differential decay rate for tsink=%d, tins=%d, aic, %s, \", err, \"Z\", iz), ", ensinfos["tsnk", ], ensinfos["tj", ], channel),
        "                  ylab=\"24 pi^3 d(DGamma / Dq^2) [GeV^-3]\", xlim=c(0, max(result$q[mask]^2))))",
        "",
        "  }",
        "}",
        "",
        "dat <- readRDS(paste0(savename, \".RDS\"))",
        sprintf("savename <- sprintf(\"tables/DG_complete_c%s_converted_%s_finvol_aic\")", nameshort[i], channel),
        "",
        "dat$DGDq2gev <- dat$DGDq2 * conversionfactor",
        "dat$dDGDq2gev <- dat$dDGDq2 * conversionfactor",
        "dat$datgev <- dat$dat * conversionfactor",
        "",
        "saveRDS(dat, paste0(savename, \".RDS\"))",
        "write.table(result, paste0(savename, \".csv\"))",
        "",
        "```",
        file=fileDG, append=TRUE, sep="\n")
    }
}


#~ for(kernel in c("sigmoid", "erf")){
#~     for(channel in c("su")) {
#~         cat(
#~ "",
#~ sprintf("```{r %s%ssetupextrapolation}", kernel, channel),
#~ "fneight <- function(par, x, boot.R, ...) par[1] + par[2] * x**2 + par[3] * x**4 + par[4] * x**6 + par[5] * x**8",
#~ "",
#~ "maxAmin <- 1",
#~ "",
#~ sprintf("files <- c(\"th2_su/%s_new/outputDGammaDq2/DGammaDq2.bin\",", kernel),
#~ sprintf("           \"th4_su/%s_new/outputDGammaDq2/DGammaDq2.bin\",", kernel),
#~ sprintf("           \"th6_su/%s_new/outputDGammaDq2/DGammaDq2.bin\",", kernel),
#~ sprintf("           \"th8_su/%s_new/outputDGammaDq2/DGammaDq2.bin\",", kernel),
#~ sprintf("           \"th9.5_su/%s_new/outputDGammaDq2/DGammaDq2.bin\",", kernel),
#~ sprintf("           \"th1/%s_new/outputDGammaDq2/DGammaDq2.bin\")", kernel),
#~ "",
#~ "th <- c(\"2_su\", \"4_su\", \"6_su\", \"8_su\", \"9.5_su\", 1)",
#~ "nerr <- rep(2, 6)",
#~ "",
#~ "par.guess <- rep(1, 5)",
#~ "",
#~ "```",
#~ file=fileDG, append=TRUE, sep="\n")
#~         for (i in seq_along(folders)) {
#~         for (i in c(1)) {
#~             folder <- folders[i]
#~                 ensinfos <- infos[folder]
#~             cat(
#~             "",
#~             sprintf("## %s %s %s", nameshort[i], channel, kernel),
#~             "### Extrapolations",
#~             "",
#~             sprintf("```{r %s%s%sextrapolatesigmatozerofinvol}", nameshort[i], kernel, channel),
#~             "",
#~             sprintf("tsnk <- rep(%d, 6)", ensinfos["tsink", ]),
#~             sprintf("Nt <- rep(%d, 6)", ensinfos["Nt", ]),
#~             "",
#~             sprintf("savename <- sprintf(\"tables/DG_complete_c%s_%s_finvol_%s\")", nameshort[i], channel, kernel),
#~             "",
#~             "par.guess <- rep(1, 5)",
#~             "",
#~             "",
#~             sprintf("determineDGDq2_all(resultpath = \"/home/gross/Documents/heavymesons/data/%s/%s/\", filenames = files, ", channel, folder),
#~             "        tsnk = tsnk, Nt = Nt, th = th, nerr = nerr, amin = maxAmin, savename = savename,",
#~             "        fitfn = fneight, par.guess = par.guess, errors=c(\"stat\", \"sys\"),",
#~             "        fitfn = fneight, par.guess = par.guess, errors=c(\"stat\", \"sys\"),",
#~             sprintf("        volumetable=\"tables/volume_interpolations/tryB64factor_%s_%s.csv\", doplot=!(knitr::is_html_output()),", channel, kernel),
#~             "        neps=19)",
#~             "",
#~             "```",
#~             "",
#~             "",
#~             "",
#~             "### Summary",
#~             "",
#~             sprintf("```{r %s%s%ssummaryfinvol}", nameshort[i], kernel, channel),
#~             "",
#~             sprintf("a <- %f", ensinfos["afm", ]),
#~             sprintf("agev <- %f / 0.1973269804 # fm / hbarc = GeV^-1", ensinfos["afm", ]),
#~             "da <- 0.00013",
#~             sprintf("am_H <- %f # dimensionless", ensinfos["ameff_calc", ]),
#~             "conversionfactor <- (am_H/agev)^3/2/pi",
#~             "",
#~             sprintf("savename <- sprintf(\"tables/DG_complete_c%s_%s_finvol_%s\")", nameshort[i], channel, kernel),
#~             "result <- read.table(paste0(savename, \".csv\"), header=TRUE)",
#~             "",
#~             "result[, c(\"DGDq2gev\", \"dDGDq2gev\")] <- result[, c(\"DGDq2\", \"dDGDq2\")] * conversionfactor",
#~             "result$q <- result$w * am_H / agev",
#~             "result$afm <- rep(a, length(result$q))",
#~             "result$dafm <- rep(da, length(result$q))",
#~             "",
#~             "for (iz in c(3, 0, 1, 2)) {",
#~             "  for (err in c(\"stat\", \"sys\")){",
#~             "  for (err in c(\"stat\", \"sys\")){",
#~             "    mask <- result$iz==iz & result$icomb==0 & result$errtype==err",
#~             "    try(plotwitherror(x=result$q[mask]^2, y=result$DGDq2gev[mask], dy=result$dDGDq2gev[mask],",
#~             sprintf("                  main=paste(\"differential decay rate for tsink=%d, tins=%d, %s, %s, \", err, \"Z\", iz), ", ensinfos["tsink", ], ensinfos["tj", ], kernel, channel),
#~             "                  xlab=\"q^2 [GeV^2]\", ylab=\"24 pi^3 DGamma / Dq^2 [GeV^-3]\",",
#~             "                  ylim=c(0, max(result$DGDq2gev[mask] + result$dDGDq2gev[mask])), xlim=c(0, max(result$q[mask]^2))))",
#~             "    ",
#~             "    try(plotwitherror(x=result$q[mask]^2, y=result$dDGDq2gev",
#~             "                  [mask],",
#~             sprintf("                  main=paste(\"differential decay rate for tsink=%d, tins=%d, %s, %s, \", err, \"Z\", iz), ", ensinfos["tsink", ], ensinfos["tj", ], kernel, channel),
#~             "                  ylab=\"24 pi^3 d(DGamma / Dq^2) [GeV^-3]\", xlim=c(0, max(result$q[mask]^2))))",
#~             "",
#~             "  }",
#~             "}",
#~             "",
#~             "dat <- readRDS(paste0(savename, \".RDS\"))",
#~             sprintf("savename <- sprintf(\"tables/DG_complete_c%s_converted_%s_finvol_%s\")", nameshort[i], channel, kernel),
#~             "",
#~             "dat$DGDq2gev <- dat$DGDq2 * conversionfactor",
#~             "dat$dDGDq2gev <- dat$dDGDq2 * conversionfactor",
#~             "dat$datgev <- dat$dat * conversionfactor",
#~             "",
#~             "saveRDS(dat, paste0(savename, \".RDS\"))",
#~             "write.table(result, paste0(savename, \".csv\"))",
#~             "",
#~             "```",
#~             file=fileDG, append=TRUE, sep="\n")
#~         }
#~     }
#~ }

#~ ## TODO: write the same for DMDq2


#~ ## TODO: write overview


#~ fileDG <- sprintf("%s/%s-summary-DGDq2.Rmd", parent, 4*length(folders)+3)
#~ fileDM <- sprintf("%s/%s-summary-DMDq2.Rmd", parent, 4*length(folders)+3)

#~ ## overview DG

#~ cat("```{r setupsummarydecayrates, include=FALSE}", 
#~ "knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, results = FALSE)", 
#~ "source(\"/home/gross/Documents/heavymesons/scripts_christiane/extrapolate_sigma_templates/functions_stability_plots.R\")", 
#~ "source(\"/home/gross/Documents/heavymesons/scripts_christiane/extrapolate_sigma_templates/calc_DGDq2.R\")", 
#~ "library(\"hadron\")", 
#~ "zlist <- c(3, 0, 1, 2)", 
#~ "errlist <- c(\"stat\", \"sys\", \"vol\", \"tot\")", 
#~ "sumup <-FALSE", 
#~ "```",
#~ "", 
#~ "# Differential Decay Rates",
#~ file=fileDG, append=FALSE, sep="\n")


#~ for(kernel in c("sigmoid", "erf")){
#~     for(channel in c("cd", "cs")) {
#~         cat(sprintf("## %s %s\n", channel, kernel),
        
#~ sprintf("```{r decayrate%sfinvol_%s}", channel, kernel), 
#~ "", 
#~ sprintf("cB64 <- read.table(\"tables/DG_complete_cB64_converted_%s_finvol_%s.csv\")", channel, kernel), 
#~ sprintf("cB96 <- read.table(\"tables/DG_complete_cB96_converted_%s_finvol_%s.csv\")", channel, kernel), 
#~ sprintf("cC80 <- read.table(\"tables/DG_complete_cC80_converted_%s_finvol_%s.csv\")", channel, kernel), 
#~ sprintf("cD96 <- read.table(\"tables/DG_complete_cD96_converted_%s_finvol_%s.csv\")", channel, kernel), 
#~ sprintf("cE112 <- read.table(\"tables/DG_complete_cE112_converted_%s_finvol_%s.csv\")", channel, kernel), 
#~ sprintf("cB48 <- read.table(\"tables/DG_complete_cB48_400_converted_%s_finvol_%s.csv\")", channel, kernel), 
#~ "", 
#~ "cB64 <- na.omit(cB64)", 
#~ "cB96 <- na.omit(cB96)", 
#~ "cC80 <- na.omit(cC80)", 
#~ "cD96 <- na.omit(cD96)", 
#~ "cE112 <- na.omit(cE112)",
#~ "cB48 <- na.omit(cB48)",  
#~ "", 
#~ "cB64 <- cB64[order(cB64$iz, cB64$errtype, cB64$icomb, cB64$q), ]", 
#~ "cB96 <- cB96[order(cB96$iz, cB96$errtype, cB96$icomb, cB96$q), ]", 
#~ "cC80 <- cC80[order(cC80$iz, cC80$errtype, cC80$icomb, cC80$q), ]", 
#~ "cD96 <- cD96[order(cD96$iz, cD96$errtype, cD96$icomb, cD96$q), ]", 
#~ "cE112 <- cE112[order(cE112$iz, cE112$errtype, cE112$icomb, cE112$q), ]", 
#~ "cB48 <- cB48[order(cB48$iz, cB48$errtype, cB48$icomb, cB48$q), ]", 
#~ "", 
#~ "", 
#~ "if(sumup) {", 
#~ "sumres <- data.frame(q=rep(0, 40), errtype=c(rep(\"stat\", 10), rep(\"sys\", 10), rep(\"vol\", 10), rep(\"tot\", 10)), ", 
#~ "                     B64DGDq2gev=rep(0, 40), B64dDGDq2gev=rep(0, 40), ", 
#~ "                     B96DGDq2gev=rep(0, 40), B96dDGDq2gev=rep(0, 40), C80DGDq2gev=rep(0, 40), ", 
#~ "                     C80dDGDq2gev=rep(0, 40), D96DGDq2gev=rep(0, 40), D96dDGDq2gev=rep(0, 40), ",
#~ "                     E112DGDq2gev=rep(0, 40), E112dDGDq2gev=rep(0, 40), B48DGDq2gev=rep(0, 40), B48dDGDq2gev=rep(0, 40))", 
#~ "}", 
#~ "", 
#~ "for(iz in zlist) {", 
#~ "  for (err in errlist){", 
#~ "    ", 
#~ "    maskB64 <- cB64$iz==iz & cB64$icomb==0 & cB64$errtype==err", 
#~ "    maskB96 <- cB96$iz==iz & cB96$icomb==0 & cB96$errtype==err", 
#~ "    maskC80 <- cC80$iz==iz & cC80$icomb==0 & cC80$errtype==err", 
#~ "    maskD96 <- cD96$iz==iz & cD96$icomb==0 & cD96$errtype==err", 
#~ "    maskE112 <- cE112$iz==iz & cE112$icomb==0 & cE112$errtype==err", 
#~ "    maskB48 <- cB48$iz==iz & cB48$icomb==0 & cB48$errtype==err", 
#~ "    ", 
#~ "    ", 
#~ "    plotwitherror(x=cB64$q[maskB64]^2, y=cB64$DGDq2gev[maskB64], dy=cB64$dDGDq2gev[maskB64],", 
#~ "                  main=paste(\"diff. decay rate , \", err, \", cd, z =\", iz), ", 
#~ "                  ylim=c(0, max(cB64$DGDq2gev[maskB64] + cB64$dDGDq2gev[maskB64], cB96$DGDq2gev[maskB96] + cB96$dDGDq2gev[maskB96], ",
#~ "                                cC80$DGDq2gev[maskC80] + cC80$dDGDq2gev[maskC80], cD96$DGDq2gev[maskD96] + cD96$dDGDq2gev[maskD96], ",
#~ "                                cE112$DGDq2gev[maskE112] + cE112$dDGDq2gev[maskE112], cB48$DGDq2gev[maskB48] + cB48$dDGDq2gev[maskB48])),", 
#~ "                  xlab=expression(paste(q^2, \" [\", GeV^2, \"]\", sep=\"\")),", 
#~ "                  ylab=\"\")", 
#~ "    mtext(side=2, text=expression(paste(\"24\", pi^3, frac(D*Gamma , D*q^2),  \"[\", GeV^-3,\"]\")), line=1.5)", 
#~ "    plotwitherror(x=cB96$q[maskB96]^2, y=cB96$DGDq2gev[maskB96], dy=cB96$dDGDq2gev[maskB96],", 
#~ "                  rep=TRUE, col=2, pch=2)", 
#~ "    plotwitherror(x=cC80$q[maskC80]^2, y=cC80$DGDq2gev[maskC80], dy=cC80$dDGDq2gev[maskC80],", 
#~ "                  rep=TRUE, col=5, pch=5)", 
#~ "    plotwitherror(x=cD96$q[maskD96]^2, y=cD96$DGDq2gev[maskD96], dy=cD96$dDGDq2gev[maskD96],", 
#~ "                  rep=TRUE, col=4, pch=4)", 
#~ "    plotwitherror(x=cE112$q[maskE112]^2, y=cE112$DGDq2gev[maskE112], dy=cE112$dDGDq2gev[maskE112],", 
#~ "                  rep=TRUE, col=6, pch=6)", 
#~ "    plotwitherror(x=cB48$q[maskB48]^2, y=cB48$DGDq2gev[maskB48], dy=cB48$dDGDq2gev[maskB48],", 
#~ "                  rep=TRUE, col=7, pch=7)", 
#~ "    legend(x=\"topleft\", legend=c(\"cB64\", \"cB96\", \"cC80\", \"cD96\", \"cE112\", \"B48\"), col=c(1, 2, 5, 4, 6, 7), pch=c(1, 2, 5, 4, 6, 7))", 
#~ "    ", 
#~ "    ", 
#~ "    if(sumup) {", 
#~ "      if(iz==0) { sumres$q[sumres$errtype==err] <- cB64$q[maskB64] }", 
#~ "      if(iz != 3) {", 
#~ "        sumres$B64DGDq2gev[sumres$errtype==err]  <- sumres$B64DGDq2gev[sumres$errtype==err]  + cB64$DGDq2gev[maskB64]", 
#~ "        sumres$B64dDGDq2gev[sumres$errtype==err] <- sumres$B64dDGDq2gev[sumres$errtype==err] + cB64$dDGDq2gev[maskB64]^2", 
#~ "        sumres$B96DGDq2gev[sumres$errtype==err]  <- sumres$B96DGDq2gev[sumres$errtype==err]  + cB96$DGDq2gev[maskB96]", 
#~ "        sumres$B96dDGDq2gev[sumres$errtype==err] <- sumres$B96dDGDq2gev[sumres$errtype==err] + cB96$dDGDq2gev[maskB96]^2", 
#~ "        sumres$C80DGDq2gev[sumres$errtype==err]  <- sumres$C80DGDq2gev[sumres$errtype==err]  + cC80$DGDq2gev[maskC80]", 
#~ "        sumres$C80dDGDq2gev[sumres$errtype==err] <- sumres$C80dDGDq2gev[sumres$errtype==err] + cC80$dDGDq2gev[maskC80]^2", 
#~ "        sumres$D96DGDq2gev[sumres$errtype==err]  <- sumres$D96DGDq2gev[sumres$errtype==err]  + cD96$DGDq2gev[maskD96]", 
#~ "        sumres$D96dDGDq2gev[sumres$errtype==err] <- sumres$D96dDGDq2gev[sumres$errtype==err] + cD96$dDGDq2gev[maskD96]^2", 
#~ "        sumres$E112DGDq2gev[sumres$errtype==err]  <- sumres$E112DGDq2gev[sumres$errtype==err]  + cE112$DGDq2gev[maskE112]", 
#~ "        sumres$E112dDGDq2gev[sumres$errtype==err] <- sumres$E112dDGDq2gev[sumres$errtype==err] + cE112$dDGDq2gev[maskE112]^2", 
#~ "        sumres$B48DGDq2gev[sumres$errtype==err]  <- sumres$B48DGDq2gev[sumres$errtype==err]  + cB48$DGDq2gev[maskB48]", 
#~ "        sumres$B48dDGDq2gev[sumres$errtype==err] <- sumres$B48dDGDq2gev[sumres$errtype==err] + cB48$dDGDq2gev[maskB48]^2", 
#~ "      }}", 
#~ "    ", 
#~ "    ", 
#~ "  }", 
#~ "}", 
#~ "## sum of Z0, Z1, Z2", 
#~ "", 
#~ "", 
#~ "if(sumup) {", 
#~ "  for (err in errlist){", 
#~ "    ", 
#~ "    plotwitherror(x=sumres$q[sumres$errtype==err]^2, y=sumres$B64DGDq2gev[sumres$errtype==err], dy=sqrt(sumres$B64dDGDq2gev[sumres$errtype==err]),", 
#~ "                  main=paste(\"diff. decay rate, \", err, \", cd, Z0+Z1+Z2\"), ", 
#~ "                  xlab=\"q^2 [GeV^2]\", ylab=\"24 pi^3 DGamma / Dq^2 [GeV^-3]\")", 
#~ "    plotwitherror(x=sumres$q[sumres$errtype==err]^2, y=sumres$B96DGDq2gev[sumres$errtype==err], ", 
#~ "                  dy=sqrt(sumres$B96dDGDq2gev[sumres$errtype==err]), rep=TRUE, col=2, pch=2)", 
#~ "    plotwitherror(x=sumres$q[sumres$errtype==err]^2, y=sumres$C80DGDq2gev[sumres$errtype==err],", 
#~ "                  dy=sqrt(sumres$C80dDGDq2gev[sumres$errtype==err]), rep=TRUE, col=5, pch=5)", 
#~ "    plotwitherror(x=sumres$q[sumres$errtype==err]^2, y=sumres$D96DGDq2gev[sumres$errtype==err], ", 
#~ "                  dy=sqrt(sumres$D96dDGDq2gev[sumres$errtype==err]), rep=TRUE, col=4, pch=4)", 
#~ "    plotwitherror(x=sumres$q[sumres$errtype==err]^2, y=sumres$E112DGDq2gev[sumres$errtype==err], ", 
#~ "                  dy=sqrt(sumres$E112dDGDq2gev[sumres$errtype==err]), rep=TRUE, col=6, pch=6)", 
#~ "    plotwitherror(x=sumres$q[sumres$errtype==err]^2, y=sumres$B48DGDq2gev[sumres$errtype==err], ", 
#~ "                  dy=sqrt(sumres$B48dDGDq2gev[sumres$errtype==err]), rep=TRUE, col=7, pch=7)", 
#~ "    legend(x=\"topleft\", legend=c(\"cB64\", \"cB96\", \"cC80\", \"cD96\", \"cE112\", \"B48\"), col=c(1, 2, 5, 4, 6, 7), pch=c(1, 2, 5, 4, 6, 7))", 
#~ "    ", 
#~ "  }", 
#~ "}", 
#~ "```\n", 
#~ file=fileDG, append=TRUE, sep="\n")
#~ }
#~ }
